name: Fortuned
version: ${project.version}
main: me.pikachow.fortuned.Main
api-version: 1.16
authors: [ pikachow ]
description: Brings the updates to the fortune enchantment into previous versions of the game! 
